### ISSUE TITLE
Add mypy

### ISSUE THREAD

**Issue by javihern98** [Meaningful-Data/vtlengine#11]
Add mypy package and typing on source code.

Add this to pyptoject.toml

```toml
[tool.mypy]
files = "src"
disallow_untyped_defs = true
disallow_untyped_calls = true
ignore_errors = false
no_implicit_optional = true
show_column_numbers = true
strict_equality = true
strict_optional = true
strict = true
enable_error_code = [
    "ignore-without-code",
    "redundant-expr",
    "truthy-bool",
]
warn_return_any = false
```
